# Generated by Django 4.1.1 on 2022-10-01 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_Name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "parent_Or_Guardian",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("DOB", models.DateField(default=django.utils.timezone.now)),
                (
                    "State",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                ("City", models.CharField(max_length=200, null=True)),
            ],
            options={
                "ordering": ["parent_Or_Guardian", "full_Name"],
            },
        ),
        migrations.CreateModel(
            name="StudentBulkUpload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_uploaded", models.DateTimeField(auto_now=True)),
                ("csv_file", models.FileField(upload_to="students/bulkupload/")),
            ],
        ),
    ]
