# Generated by Django 4.1.1 on 2022-10-01 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_auto_20201124_0614"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={},
        ),
        migrations.RenameField(
            model_name="student",
            old_name="firstname",
            new_name="full_Name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="address",
        ),
        migrations.RemoveField(
            model_name="student",
            name="current_class",
        ),
        migrations.RemoveField(
            model_name="student",
            name="date_of_admission",
        ),
        migrations.RemoveField(
            model_name="student",
            name="other_name",
        ),
        migrations.RemoveField(
            model_name="student",
            name="others",
        ),
        migrations.RemoveField(
            model_name="student",
            name="parent_mobile_number",
        ),
        migrations.RemoveField(
            model_name="student",
            name="passport",
        ),
        migrations.RemoveField(
            model_name="student",
            name="registration_number",
        ),
        migrations.RemoveField(
            model_name="student",
            name="surname",
        ),
    ]
