# Generated by Django 4.1.1 on 2022-10-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_alter_student_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="gender",
        ),
        migrations.AddField(
            model_name="student",
            name="city",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
